# -*- coding: utf-8 -*-
"""Imputación base RESULTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ms6t7LtMoyfjejXiq-29C8Tvjlmio1NI

# 1 CARGA
"""

import pandas as pd
import numpy as np

rts = pd.read_csv("RESULTS.csv")
rs = pd.read_csv("RACES.csv", encoding='latin1')
ds= pd.read_csv("DRIVER_STANDINGS.csv")
ps= pd.read_csv("PIT_STOPS.csv")
sc= pd.read_csv("SAFETY_CAR.csv")
lt= pd.read_csv("LAP_TIMES.csv")

"""# 2 EXPLORACIÓN"""

rts.head()
rts.shape
rts.info()
rts.describe()

"""# 3. AUDITORÍA"""

print("Duplicados:", rts.duplicated().sum())

print("\nValores nulos:")
print(rts.isnull().sum())

print("\nTipos de datos:")
print(rts.dtypes)

"""TIME,RANK, FASTESTLAPTIME, FASTESTLAPSPEED = \N"""

print(f"El puntaje más alto en la columna 'POINTS' es: {rts['POINTS'].max()}")

rts['RANK'].value_counts().to_frame()

"""la suma de todos los LAPS + todos los PITSTOPS me tiene que dar RESULTS

# 4. LIMPIEZA
"""

rts = rts.merge(rs[['RACEID','YEAR']], on='RACEID', how='left')

rts['YEAR_x'] = rts['YEAR_x'].fillna(rts['YEAR_y'])

rts = rts.drop(columns=['YEAR_y'])
rts = rts.rename(columns={'YEAR_x':'YEAR'})

rts = rts.merge(rs[['RACEID','ROUND']], on='RACEID', how='left')

rts['ROUND_x'] = rts['ROUND_x'].fillna(rts['ROUND_y'])

rts = rts.drop(columns=['ROUND_y'])
rts = rts.rename(columns={'ROUND_x':'ROUND'})

rts = rts.merge(rs[['RACEID','NAME']], on='RACEID', how='left')

rts['NAME_x'] = rts['NAME_x'].fillna(rts['NAME_y'])

rts = rts.drop(columns=['NAME_y'])
rts = rts.rename(columns={'NAME_x':'NAME'})

rts['POINTS_CHAR'] = rts['POINTS_CHAR'].fillna(
    rts['POINTS'].astype(str) + " points"
)

rts['F1NUM'] = rts['F1NUM'].replace({'\\N': np.nan})

rts['TIME'] = rts['TIME'].replace('\\N', np.nan)

rts['RANK'] = rts['RANK'].replace('\\N', np.nan)

# rellene los valores faltantes con un marcador de posición como 1 o 999 para indicar que el conductor no terminó, fue descalificado o su posición no fue registrada.
rts['POSITION'] = rts['POSITION'].fillna(-1)

rts['F1NUM'].value_counts().to_frame()

rts["POSITION"] = pd.to_numeric(rts["POSITION"], errors="coerce")

rts["TIME"] = pd.to_numeric(rts["TIME"], errors="coerce")

rts['YEAR'] = rts['YEAR'].astype(int)

# asignamos un 0 (indicando "Sin número asignado").
rts['F1NUM'] = rts['F1NUM'].replace(r"\\N", np.nan)
rts['F1NUM'] = pd.to_numeric(rts['F1NUM'], errors='coerce').fillna(0).astype(int)

rts['POSITION'] = rts['POSITION'].fillna(-1)

"""# 5. TRANSFORMACIONES"""

print(rts.info())
print("\nValores nulos finales:")
print(rts.isnull().sum())
print("\nDimensiones finales:")
print(rts.shape)

print(rts.info())
print("\nValores nulos finales:")
print(rts.isnull().sum())
print("\nDimensiones finales:")
print(rts.shape)

import pandas as pd
import numpy as np

# 1. CARGA DE DATOS
# Asumiendo que ya tienes rts (RESULTS) y lt (LAP_TIMES) cargados
# rts = pd.read_csv('RESULTS.csv')
# lt = pd.read_csv('LAP_TIMES.csv')

# Pre-limpieza: Convertir \N a NaN y asegurar tipos numéricos
rts['FASTESTLAPTIME'] = rts['FASTESTLAPTIME'].replace(r"\\N", np.nan)
rts['FASTESTLAPSPEED'] = pd.to_numeric(rts['FASTESTLAPSPEED'].replace(r"\\N", np.nan), errors='coerce')
lt['MILLISECONDS'] = pd.to_numeric(lt['MILLISECONDS'], errors='coerce')

print(f"Nulos iniciales - Time: {rts['FASTESTLAPTIME'].isna().sum()}, Speed: {rts['FASTESTLAPSPEED'].isna().sum()}")

# 2. PROCESAMIENTO DE FASTESTLAPTIME (Usando LAP_TIMES)
# Encontramos el tiempo mínimo (vuelta más rápida) por carrera y piloto
fastest_by_lap = lt.groupby(['RACEID', 'DRIVERID'])['MILLISECONDS'].min().reset_index()

# Función para convertir MS a formato de tiempo (MM:SS.mmm)
def ms_to_f1_format(ms):
    if pd.isna(ms) or ms == 0: return np.nan
    minutes = int(ms // 60000)
    seconds = (ms % 60000) / 1000
    return f"{minutes:02d}:{seconds:06.3f}"[:-1]

fastest_by_lap['TIME_CALCULATED'] = fastest_by_lap['MILLISECONDS'].apply(ms_to_f1_format)

# 3. PROCESAMIENTO DE FASTESTLAPSPEED (Opción B: Promedio por carrera)
# Calculamos el promedio de velocidad de los que SÍ tienen dato en cada carrera
race_speed_avg = rts.groupby('RACEID')['FASTESTLAPSPEED'].transform('mean')

# 4. MERGE E IMPUTACIÓN
# Unimos los tiempos calculados de LAP_TIMES
rts = rts.merge(fastest_by_lap[['RACEID', 'DRIVERID', 'TIME_CALCULATED']],
                on=['RACEID', 'DRIVERID'], how='left')

# Imputación de TIME: Si es nulo en original, usa el calculado de LAP_TIMES
rts['FASTESTLAPTIME'] = rts['FASTESTLAPTIME'].fillna(rts['TIME_CALCULATED'])

# Imputación de SPEED: Si es nulo, usa el promedio de esa carrera
rts['FASTESTLAPSPEED'] = rts['FASTESTLAPSPEED'].fillna(race_speed_avg)

# 5. LIMPIEZA DE OUTLIERS (Propuesta adicional)
# Si después de imputar la velocidad es < 100km/h o > 260km/h (promedio histórico),
# podría ser un outlier por Safety Car o condiciones extremas.
# Aquí marcamos como 0 lo que siga siendo nulo (ej. pilotos que no dieron ni 1 vuelta)
rts['FASTESTLAPSPEED'] = rts['FASTESTLAPSPEED'].fillna(0)
rts['FASTESTLAPTIME'] = rts['FASTESTLAPTIME'].fillna("00:00.0")

# Eliminar columna auxiliar
rts.drop(columns=['TIME_CALCULATED'], inplace=True)

print(f"Nulos finales - Time: {rts['FASTESTLAPTIME'].replace('00:00.0', np.nan).isna().sum()}")
print(f"Nulos finales - Speed: {rts['FASTESTLAPSPEED'].replace(0, np.nan).isna().sum()}")

import pandas as pd
import numpy as np

# 1. CARGA Y LIMPIEZA INICIAL
# rts = pd.read_csv("RESULTS.csv")

# Convertir \N a NaN y asegurar que sea numérico
rts['RANK'] = pd.to_numeric(rts['RANK'].replace(r"\\N", np.nan), errors='coerce')

print(f"Nulos iniciales en RANK: {rts['RANK'].isna().sum()}")

# 2. CALCULAR RANKING ALTERNATIVO (Basado en Desempeño)
# Creamos un ranking basado en: 1. Puntos (desc), 2. Posición Final (asc)
# Esto garantiza que todos los pilotos tengan una jerarquía lógica.

rts['RANK_DESEMPENO'] = rts.groupby('RACEID').apply(
    lambda x: x[['POINTS', 'POSITIONORDER']].apply(tuple, axis=1)
             .rank(method='min', ascending=False)
).reset_index(level=0, drop=True)

# 3. IMPUTACIÓN ESTRATÉGICA
# Solo llenamos donde RANK original es nulo
rts['RANK'] = rts['RANK'].fillna(rts['RANK_DESEMPENO'])

# 4. VALIDACIÓN DE SECUENCIA
# Aseguramos que sea entero y manejamos casos extremos
rts['RANK'] = rts['RANK'].astype(int)

# 5. RESULTADOS
print(f"Nulos finales en RANK: {rts['RANK'].isna().sum()}")

# Ejemplo de validación: Una carrera específica (ej: RACEID 873)
ejemplo_carrera = rts[rts['RACEID'] == 873][['NAME', 'DRIVERID', 'POSITIONORDER', 'POINTS', 'RANK']].sort_values('RANK')
print("\nEjemplo de Ranking reconstruido para una carrera:")
print(ejemplo_carrera.head(10))

import pandas as pd
import numpy as np

# 1. Preparación de datos y limpieza de nulos en SCORE (si existe)
# rts = pd.read_csv("RESULTS.csv")

# Aseguramos que POSITION sea numérico para detectar nulos correctamente
rts['POSITION'] = pd.to_numeric(rts['POSITION'].replace(r"\\N", np.nan), errors='coerce')

print(f"Nulos iniciales en POSITION: {rts['POSITION'].isna().sum()}")

# 2. CÁLCULO DE POSICIÓN RECONSTRUIDA
# Creamos un ranking de desempeño por carrera (RACEID)
# Ordenamos por: Mayor cantidad de vueltas (LAPS) y mejor POSITIONORDER
def calculate_position_logic(group):
    # Generamos un ranking del 1 al N basado en el desempeño real
    # ascending=False para LAPS (más es mejor)
    # ascending=True para POSITIONORDER (1 es mejor que 20)
    return group[['LAPS', 'POSITIONORDER']].apply(tuple, axis=1) \
                 .rank(method='first', ascending=True)

# Aplicamos la lógica por carrera
rts['POSITION_RANKED'] = rts.groupby('RACEID', group_keys=False).apply(
    lambda x: x.sort_values(['LAPS', 'POSITIONORDER'], ascending=[False, True]) \
               .assign(temp_rank=range(1, len(x) + 1))['temp_rank']
)

# 3. IMPUTACIÓN SELECTIVA
# Solo llenamos los nulos, manteniendo los valores originales de la FIA
rts['POSITION'] = rts['POSITION'].fillna(rts['POSITION_RANKED'])

# Convertimos a entero para limpieza visual
rts['POSITION'] = rts['POSITION'].astype(int)

# 4. VALIDACIÓN
print(f"Nulos finales en POSITION: {rts['POSITION'].isna().sum()}")

# Ejemplo de una carrera reconstruida (RACEID 873 - Singapur 2012)
ejemplo = rts[rts['RACEID'] == 873][['NAME', 'DRIVERID', 'LAPS', 'POSITIONORDER', 'POSITION']].sort_values('POSITION')
print("\nEjemplo de carrera reconstruida (Top 10):")
print(ejemplo.head(10))

print(rts.info())
print("\nValores nulos finales:")
print(rts.isnull().sum())
print("\nDimensiones finales:")
print(rts.shape)

"""#JUNTAR BASES

##LT y rts
"""

import pandas as pd
import numpy as np

# 1. Limpieza de datos (asegurar que sean numéricos)
rts['RACEID'] = pd.to_numeric(rts['RACEID'], errors='coerce')
rts['DRIVERID'] = pd.to_numeric(rts['DRIVERID'], errors='coerce')
lt['RACEID'] = pd.to_numeric(lt['RACEID'], errors='coerce')
lt['DRIVERID'] = pd.to_numeric(lt['DRIVERID'], errors='coerce')
lt['MILLISECONDS'] = pd.to_numeric(lt['MILLISECONDS'], errors='coerce')

# Convertir MILLISECONDS de rts a numérico. Los valores '\N' ya se manejaron antes y se imputaron con 0 o nan.
rts['MILLISECONDS'] = pd.to_numeric(rts['MILLISECONDS'], errors='coerce')

# 2. CALCULAR EL TIEMPO ACUMULADO REAL EN LAP_TIMES
# Sumamos todos los milisegundos que existan para cada par Piloto-Carrera
# Sin importar si terminó la carrera o no, sumamos lo que haya.
tiempos_acumulados = lt.groupby(['RACEID', 'DRIVERID'])['MILLISECONDS'].sum().reset_index()
tiempos_acumulados.rename(columns={'MILLISECONDS': 'MS_TOTAL_LT'}, inplace=True)

# 3. HACER EL JOIN
# Traemos esa suma a la tabla RESULTS (rts)
rts = rts.merge(tiempos_acumulados, on=['RACEID', 'DRIVERID'], how='left')

# 4. RELLENO MASIVO
# Si el original es nulo, usamos la suma de todas las vueltas encontradas en LAP_TIMES
rts['MILLISECONDS'] = rts['MILLISECONDS'].fillna(rts['MS_TOTAL_LT'])

# 5. EL PARCHE FINAL (Lógica de Negocio)
# Para los casos que siguen siendo nulos tras el join (porque no existen en LAP_TIMES),
# la única forma de tener 0 nulos es imputar por el desempeño de la carrera.
# Usamos el promedio de milisegundos por vuelta de esa carrera multiplicado por las vueltas del piloto.

# Calculamos el tiempo promedio por vuelta de cada carrera (usando los datos que sí tenemos)
avg_lap_ms = rts[rts['MILLISECONDS'] > 0].groupby('RACEID')['MILLISECONDS'].sum() / \
             rts[rts['MILLISECONDS'] > 0].groupby('RACEID')['LAPS'].sum()
avg_lap_ms = avg_lap_ms.reset_index().rename(columns={0: 'AVG_MS_PER_LAP'})

# Unimos este promedio a la tabla
rts = rts.merge(avg_lap_ms, on='RACEID', how='left')

# Imputamos los últimos nulos: Vueltas del piloto * Promedio de tiempo de esa carrera
rts['MILLISECONDS'] = rts['MILLISECONDS'].fillna(rts['LAPS'] * rts['AVG_MS_PER_LAP'])

# 6. LIMPIEZA TOTAL
# Si aún queda algo (carreras sin ningún dato de tiempo), ponemos 0 para llegar a 0 nulos.
rts['MILLISECONDS'] = rts['MILLISECONDS'].fillna(0)

# Borramos columnas auxiliares
rts.drop(columns=['MS_TOTAL_LT', 'AVG_MS_PER_LAP'], inplace=True)

print(f"Conteo final de nulos en MILLISECONDS: {rts['MILLISECONDS'].isna().sum()}")

rts

rts.isnull().sum()

"""##ps y rts"""

import pandas as pd
import numpy as np

# 1. Agrupamos PIT_STOPS para obtener la suma de milisegundos por carrera y piloto
# Usamos directamente las columnas 'milliseconds', 'RACEID' y 'DRIVERID'
pit_sums = ps.groupby(['RACEID', 'DRIVERID'])['MILLISECONDS'].sum().reset_index()

# 2. Hacemos el merge con rts
# Nota: Asegúrate de que los nombres de las columnas coincidan (ej: RACEID o raceId)
rts = rts.merge(pit_sums, left_on=['RACEID', 'DRIVERID'], right_on=['RACEID', 'DRIVERID'], how='left')

# 3. Función de conversión a formato de tiempo (hh:mm:ss.mmm)
def ms_to_f1(ms):
    if pd.isna(ms) or ms <= 0:
        return np.nan
    total_sec = ms / 1000
    h = int(total_sec // 3600)
    m = int((total_sec % 3600) // 60)
    s = total_sec % 60
    if h > 0:
        return f"{h}:{m:02d}:{s:06.3f}"[:-1]
    else:
        return f"{m:02d}:{s:06.3f}"[:-1]

# 4. Imputación directa en la columna TIME original
# Sumamos MILLISECONDS (pista) + MILLISECONDS (boxes) y rellenamos nulos
rts['TIME'] = rts['TIME'].fillna(
    (rts['MILLISECONDS_x'] + rts['MILLISECONDS_y'].fillna(0)).apply(ms_to_f1)
)

# 5. Eliminamos las columnas sobrantes del merge para mantener la estructura original
rts.drop(columns=['MILLISECONDS_y'], inplace=True)
rts.rename(columns={'MILLISECONDS_x': 'MILLISECONDS'}, inplace=True)

print(f"Proceso finalizado. Nulos en TIME: {rts['TIME'].isna().sum()}")

rts.isnull().sum()

"""Ese residuo de 2,494 nulos es el "ruido histórico" inevitable del dataset. Aquí explicamos por qué ya no bajan más y qué representan esos datos:

1. El origen de los 2,494 nulos restantes
Carreras anteriores a 1996: Los archivos de LAP_TIMES y PIT_STOPS suelen tener datos consistentes a partir de mediados de los 90. Para las décadas de los 50 a los 80, no hay registros electrónicos de vueltas o paradas para sumar.
"""

rts.to_csv('rts_processed.csv', index=False)
print("DataFrame 'rts' saved to 'rts_processed.csv'")