# -*- coding: utf-8 -*-
"""Limpieza_DRIVER_STANDINGS (3).ipynb .

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jK_edRJpxI4fYLmyGXlh30oUAnhrlPvC

# 1. CARGA DE DATOS
"""


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

from sklearn.preprocessing import StandardScaler, MinMaxScaler


from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.neural_network import MLPRegressor # MLP = multi layer perceptron
from sklearn.svm import SVR

def audit_df(df,name):

  print(f"\n {"="*60}")
  print(f"DATASET: {name}")
  print(f"\n {"="*60}")

  print("Dimensiones: ",df.shape)
  print("Duplicados: ",df.duplicated().sum())

  print(f"\n Tipo de datos: ")
  print(df.dtypes)

  print(f"\n Datos nulos: ")
  print(df.isnull().sum())

  print("\n Resumen Estadistico:")
  display(df.describe(include='all'))

pd.set_option('display.max_columns', None)
ds = pd.read_csv('DRIVER_STANDINGS.csv')
ds.head()

rs = pd.read_csv("RACES.csv", encoding='latin1')

lt = pd.read_csv('LAP_TIMES.csv')

"""#2. EXPLORACIÓN

"""

print("Info for Driver Standings DataFrame:")
ds.info()
print("\nDescriptive statistics for Driver Standings DataFrame:")
ds.describe()

print("Missing values in Driver Standings DataFrame:")
ds.isnull().sum()

print(f"The driver_standings DataFrame has {ds.shape[0]} rows.")

"""# 3. AUDITORÍA"""

ds=pd.read_csv("DRIVER_STANDINGS.csv")
audit_df(ds,"DRIVER STANDINGS")



"""#4. LIMPIEZA

## YEAR DS Y RS
"""

ds = ds.merge(rs[['RACEID','YEAR']], on='RACEID', how='left', suffixes=('_x', '_y'))

ds['YEAR_x'] = ds['YEAR_x'].fillna(ds['YEAR_y'])

ds = ds.drop(columns=['YEAR_y'])
ds = ds.rename(columns={'YEAR_x':'YEAR'})

# Definimos los datos que faltan para el RACEID 1074
datos_1074 = {
    'YEAR': 2022,
    'ROUND': 4,
    'NAME': 'Emilia Romagna Grand Prix'
}

# Aplicamos el parche solo donde el RACEID sea 1074
ds.loc[ds['RACEID'] == 1074, ['YEAR', 'ROUND', 'NAME']] = \
    datos_1074['YEAR'], datos_1074['ROUND'], datos_1074['NAME']

# Verificamos que ya no haya nulos
print(f"Nulos restantes: {ds[['YEAR', 'ROUND', 'NAME']].isnull().sum().sum()}")

# Convertir a entero para quitar el .0 (estética y limpieza)
ds['YEAR'] = ds['YEAR'].astype(pd.Int64Dtype())
ds['ROUND'] = ds['ROUND'].astype(pd.Int64Dtype())

# Mostrar las primeras filas para celebrar el éxito
print(ds[ds['RACEID'] == 1074].head())

# Ver qué RACEIDs en driver_standings no tienen correspondencia en races
nulos = ds[ds['YEAR'].isnull()]
ids_faltantes = nulos['RACEID'].unique()
print(f"Los RACEID que no cruzaron son: {ids_faltantes}")

"""## ROUND"""

ds = ds.merge(rs[['RACEID','ROUND']], on='RACEID', how='left')

ds['ROUND_x'] = ds['ROUND_x'].fillna(ds['ROUND_y'])

ds = ds.drop(columns=['ROUND_y'])
ds = ds.rename(columns={'ROUND_x':'ROUND'})

"""## NAME"""

ds = ds.merge(rs[['RACEID','NAME']], on='RACEID', how='left')

ds['NAME_x'] = ds['NAME_x'].fillna(ds['NAME_y'])

ds = ds.drop(columns=['NAME_y'])
ds = ds.rename(columns={'NAME_x':'NAME'})

"""## DRIVERREFF (ds & lt)"""

#mapeo con DRIVERID
driver_map = ds.dropna(subset=['DRIVERREF']).set_index('DRIVERID')['DRIVERREF'].to_dict()

ds['DRIVERREF'] = ds['DRIVERREF'].fillna(ds['DRIVERID'].map(driver_map))

ds['DRIVERREF'].isnull().sum()

## Ver qué IDs no tienen apellido asignado
ds[ds['DRIVERREF'].isnull()]['DRIVERID'].unique()

ds[ds['DRIVERREF'].isnull()]['DRIVERID'].value_counts()

"""LAP_TIMES"""

ids_a_buscar = [852, 853, 854, 855]
drivers_en_lt = lt[lt['DRIVERID'].isin(ids_a_buscar)]

if not drivers_en_lt.empty:
    print(f"Los siguientes DRIVERID faltantes se encontraron en LAP_TIMES:")
    for driver_id in ids_a_buscar:
        driver_data = drivers_en_lt[drivers_en_lt['DRIVERID'] == driver_id]
        if not driver_data.empty:
            driver_refs = driver_data['DRIVERREF'].dropna().unique()
            if len(driver_refs) > 0:
                print(f"- DRIVERID {driver_id} tiene DRIVERREF: {driver_refs[0]}")
            else:
                print(f"- DRIVERID {driver_id} se encontró pero no tiene DRIVERREF.")
        else:
            print(f"- DRIVERID {driver_id} no se encontró en LAP_TIMES.")
else:
    print(f"Ninguno de los DRIVERID {ids_a_buscar} se encontró en LAP_TIMES.")

# 1. Preparamos una tabla pequeña con la "verdad" de LAP_TIMES
# Solo queremos una lista de IDs y sus nombres, sin duplicados
df_nombres_extra = lt[['DRIVERID', 'DRIVERREF']].drop_duplicates(subset=['DRIVERID'])

# 2. Hacemos el LEFT JOIN
# Unimos ds con nuestra tabla pequeña usando DRIVERID como llave
ds = ds.merge(df_nombres_extra, on='DRIVERID', how='left', suffixes=('', '_FROM_LAP'))

# 3. Llenamos los nulos de la columna original SOLO con los datos nuevos
# Esto asegura que no toquemos a Michael Schumacher ni a otros que ya estaban bien
ds['DRIVERREF'] = ds['DRIVERREF'].fillna(ds['DRIVERREF_FROM_LAP'])

# 4. Eliminamos la columna auxiliar que creó el join para dejar la base limpia
ds.drop(columns=['DRIVERREF_FROM_LAP'], inplace=True)

# 5. Corrección específica para el apellido que querías normalizar
# Solo cambiamos 'mick_schumacher' por 'schumacher'
ds['DRIVERREF'] = ds['DRIVERREF'].replace({'mick_schumacher': 'schumacher'})

# Verificación
print("Nulos restantes:", ds['DRIVERREF'].isnull().sum())
print("Nombres recuperados:", ds[ds['DRIVERID'].isin([852, 853, 854])]['DRIVERREF'].unique())

ds['DRIVERREF'] = ds['DRIVERREF'].str.replace('_', ' ', regex=False)

nombres_compuestos = ds[ds['DRIVERREF'].str.contains('_', na=False)]['DRIVERREF'].unique()
if len(nombres_compuestos) > 0:
    print("Los siguientes 'DRIVERREF' aún contienen el formato 'nombre_apellido' (con guion bajo):")
    for nombre in nombres_compuestos:
        print(f"- {nombre}")
else:
    print("Todos los 'DRIVERREF' que contenían un guion bajo han sido procesados.")

ds = ds[ds['DRIVERID'] != 855]

"""## FINAL

cambiar FINAL a binary
"""

ds['FINAL'].unique()

ds['FINAL'] = ds['FINAL'].map({'Y': 1, 'N': 0})
ds['FINAL'] = ds['FINAL'].astype(pd.Int64Dtype())

"""Dado que la columna indica si los puntos son definitivos para la temporada, el valor suele ser 1 (Y) cuando se trata de la última carrera del año y 0 (N) para las carreras intermedias.

Se puede identificar la última carrera de cada año y rellenar en consecuencia.
"""

# 1. Encontrar la ronda máxima por cada año
last_rounds = ds.groupby('YEAR')['ROUND'].max()

# 2. Función para determinar si es final basado en la ronda
def determinar_final(row):
    if pd.isnull(row['FINAL']):
        # Si la ronda de la fila es la última del año, es Final (1)
        if row['ROUND'] == last_rounds[row['YEAR']]:
            return 1
        else:
            return 0
    return row['FINAL']

# 3. Aplicar a las filas nulas
ds['FINAL'] = ds.apply(determinar_final, axis=1)

"""## DRIVER_POSITION_BEFORE_RACE & DRIVER_POINTS_BEFORE_RACE (ambas variables tienen los mismos datos nulos)"""

# 1. Es CRUCIAL ordenar los datos cronológicamente para que el "desplazamiento" sea correcto
ds = ds.sort_values(by=['DRIVERID', 'YEAR', 'ROUND'])

# 2. Llenamos los puntos antes de la carrera con los puntos acumulados de la carrera anterior
# Agrupamos por piloto para no mezclar puntos de personas distintas
ds['DRIVER_POINTS_BEFORE_RACE'] = ds['DRIVER_POINTS_BEFORE_RACE'].fillna(
    ds.groupby('DRIVERID')['POINTS'].shift(1)
)

# 3. Llenamos la posición antes de la carrera con la posición de la carrera anterior
ds['DRIVER_POSITION_BEFORE_RACE'] = ds['DRIVER_POSITION_BEFORE_RACE'].fillna(
    ds.groupby('DRIVERID')['POSITION'].shift(1)
)

# 4. Los casos que sigan siendo nulos (que serán las rondas 1 de cada piloto) los llenamos con 0
ds['DRIVER_POINTS_BEFORE_RACE'] = ds['DRIVER_POINTS_BEFORE_RACE'].fillna(0)
ds['DRIVER_POSITION_BEFORE_RACE'] = ds['DRIVER_POSITION_BEFORE_RACE'].fillna(0)

print(f"Nulos en Puntos: {ds['DRIVER_POINTS_BEFORE_RACE'].isnull().sum()}")
print(f"Nulos en Posición: {ds['DRIVER_POSITION_BEFORE_RACE'].isnull().sum()}")

"""sort_values: Asegura que el historial de cada piloto esté en orden (Carrera 1, luego Carrera 2...).

groupby('DRIVERID'): Evita que los puntos finales de "Hamilton" se le asignen como puntos iniciales a "Alonso". Todo se queda dentro del mismo piloto.

.shift(1): Toma el valor de la fila anterior (el resultado final de la carrera pasada) y lo proyecta a la fila actual como el estado "antes de la carrera".

fillna(0): Es probable que te queden algunos nulos después del shift. Esto ocurre en la primera carrera de la historia de cada piloto en el dataset, donde no hay una "carrera anterior". En ese caso, lo correcto es poner 0 porque empezaron la temporada sin puntos.

## POSITION_POINTS_BEFORE_RACE

la situación de un piloto al "llegar" a un Gran Premio es exactamente la misma con la que "se fue" del Gran Premio anterior.
"""

# 1. Aseguramos el orden (por si acaso se movió algo antes)
ds = ds.sort_values(by=['DRIVERID', 'YEAR', 'ROUND'])

# 2. Llenamos con el valor de POINTS de la fila (carrera) anterior
ds['POSITION_POINTS_BEFORE_RACE'] = ds['POSITION_POINTS_BEFORE_RACE'].fillna(
    ds.groupby('DRIVERID')['POINTS'].shift(1)
)

# 3. Para los pilotos en su debut o primera carrera del año sin historial previo, ponemos 0
ds['POSITION_POINTS_BEFORE_RACE'] = ds['POSITION_POINTS_BEFORE_RACE'].fillna(0)

print(f"Nulos restantes en POSITION_POINTS_BEFORE_RACE: {ds['POSITION_POINTS_BEFORE_RACE'].isnull().sum()}")

ds.isnull().sum()

"""## POSITION TEXT ELIMINADO"""

eliminate = ds.drop(columns=['POSITIONTEXT'])

"""## POINTS_OF_LOWER_POSITION

En el contexto de los standings de F1, esto representa los puntos que tiene el piloto que está justo debajo de nuestro piloto en la tabla de posiciones en ese momento.
"""

# 1. Crear una referencia de puntos por posición para cada carrera
# Esto crea un mapa de (RACEID, POSITION) -> POINTS
puntos_por_posicion = ds.set_index(['RACEID', 'POSITION'])['POINTS'].to_dict()

# 2. Función para buscar los puntos del piloto de la posición siguiente
def conseguir_puntos_inferior(row):
    if pd.isnull(row['POINTS_OF_LOWER_POSITION']):
        # Buscamos en la misma carrera (RACEID) al que tiene la posición + 1
        return puntos_por_posicion.get((row['RACEID'], row['POSITION'] + 1))
    return row['POINTS_OF_LOWER_POSITION']

# 3. Aplicamos la función
ds['POINTS_OF_LOWER_POSITION'] = ds.apply(conseguir_puntos_inferior, axis=1)

# 4. Los que queden nulos después de esto son los que realmente son ÚLTIMOS en la tabla
# Para ellos, lo lógico es que el de abajo tenga 0 puntos o dejarlo como 0.
ds['POINTS_OF_LOWER_POSITION'] = ds['POINTS_OF_LOWER_POSITION'].fillna(0)

print(f"Nulos restantes en POINTS_OF_LOWER_POSITION: {ds['POINTS_OF_LOWER_POSITION'].isnull().sum()}")

"""¿Por qué esta solución es la mejor?
Es dinámica: No asume un valor fijo, sino que mira quién estaba debajo de ese piloto en esa carrera específica.

Usa datos reales: Si en la Carrera A, el piloto en P5 tenía 10 puntos, nuestro piloto en P4 ahora tendrá correctamente "10" en sus POINTS_OF_LOWER_POSITION.

Maneja el final de la tabla: El fillna(0) final es correcto porque si eres el último (por ejemplo, posición 20), no hay nadie debajo de ti, por lo que los puntos de la "posición inferior" son inexistentes (0).

## POINTS_OF_LOWER_POSITION_BEFORE_RACE
"""

# 1. Ordenamos cronológicamente por piloto
ds = ds.sort_values(by=['DRIVERID', 'YEAR', 'ROUND'])

# 2. Aplicamos el desplazamiento (shift):
# Lo que era "puntos del de abajo" al final de la carrera pasada,
# es ahora "puntos del de abajo antes de esta carrera".
ds['POINTS_OF_LOWER_POSITION_BEFORE_RACE'] = ds['POINTS_OF_LOWER_POSITION_BEFORE_RACE'].fillna(
    ds.groupby('DRIVERID')['POINTS_OF_LOWER_POSITION'].shift(1)
)

# 3. Para los debuts de los pilotos (donde no hay historial previo), llenamos con 0
ds['POINTS_OF_LOWER_POSITION_BEFORE_RACE'] = ds['POINTS_OF_LOWER_POSITION_BEFORE_RACE'].fillna(0)

print(f"Nulos restantes en POINTS_OF_LOWER_POSITION_BEFORE_RACE: {ds['POINTS_OF_LOWER_POSITION_BEFORE_RACE'].isnull().sum()}")

"""toma los puntos del piloto de abajo de la carrera anterior y los asigna como el valor inicial del piloto actual, asegurando la continuidad histórica de su competencia directa

## DELTA_POINTS_TO_LOWER_POSITION, DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE	 & CHANGE_DELTA_BEFORE_AND_AFTER_RACE

DELTA_POINTS_TO_LOWER_POSITION: Es la diferencia de puntos con el de abajo al terminar la carrera.

DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE: Es esa misma diferencia pero antes de empezar la carrera.

CHANGE_DELTA_BEFORE_AND_AFTER_RACE: Es simplemente la resta entre las dos anteriores (cuánto cambió esa brecha durante la carrera).
"""

# 1. Resolver DELTA_POINTS_TO_LOWER_POSITION (Diferencia actual)
# Lógica: Mis puntos actuales menos los puntos del de abajo (que ya limpiamos)
ds['DELTA_POINTS_TO_LOWER_POSITION'] = ds['DELTA_POINTS_TO_LOWER_POSITION'].fillna(
    ds['POINTS'] - ds['POINTS_OF_LOWER_POSITION']
)

# 2. Resolver DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE (Diferencia histórica)
# Lógica: Es el DELTA que había al final de la carrera anterior
ds = ds.sort_values(by=['DRIVERID', 'YEAR', 'ROUND'])
ds['DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE'] = ds['DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE'].fillna(
    ds.groupby('DRIVERID')['DELTA_POINTS_TO_LOWER_POSITION'].shift(1)
)
# Si es el debut del piloto, la diferencia inicial es 0
ds['DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE'] = ds['DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE'].fillna(0)

# 3. Resolver CHANGE_DELTA_BEFORE_AND_AFTER_RACE (El cambio neto)
# Lógica: Diferencia final menos diferencia inicial
ds['CHANGE_DELTA_BEFORE_AND_AFTER_RACE'] = ds['CHANGE_DELTA_BEFORE_AND_AFTER_RACE'].fillna(
    ds['DELTA_POINTS_TO_LOWER_POSITION'] - ds['DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE']
)

print(ds[['DELTA_POINTS_TO_LOWER_POSITION', 'DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE', 'CHANGE_DELTA_BEFORE_AND_AFTER_RACE']].isnull().sum())

"""#5. CONVERSIÓN DE TIPOS"""

ds["POSITION"] = pd.to_numeric(ds["POSITION"], errors="coerce")

"""#8 ESCALADO"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
ds[["POINTS"]] = scaler.fit_transform(ds[["POINTS"]])

"""checar los puntos que se usan en f1 y a que se refieren

#10 VALIDACIÓN FINAL
"""

ds.info()

ds.isnull().sum()

ds.describe()

ds.head()

ds.to_csv('base_final_DS33.csv', index=False)

"""# correlación"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# 1. CARGA DE DATOS
# ---------------------------------------------------------
# Cargamos las bases principales
races = pd.read_csv('rcs_transformed.csv', encoding='latin1')
drivers = pd.read_csv('base_final_DS33.csv')

# Aseguramos que SCORE sea numérico para evitar errores en la correlación
races['SCORE'] = pd.to_numeric(races['SCORE'], errors='coerce')

# ---------------------------------------------------------
# 2. SELECCIÓN DE VARIABLES ESPECÍFICAS
# ---------------------------------------------------------
# Definimos las variables exactas que quieres analizar de la base de drivers
variables_drivers = [
    'RACEID',
    'DRIVER_POINTS_BEFORE_RACE',
    'POINTS',
    'POSITION_POINTS_BEFORE_RACE'
]

# Creamos un subconjunto solo con esas columnas para evitar conflictos
drivers_subset = drivers[variables_drivers].copy()

# ---------------------------------------------------------
# 3. MERGING (Unión por RACEID)
# ---------------------------------------------------------
# Unimos el SCORE de rcs_transformed con las variables de base_final_DS33
# Usamos RACEID como llave de unión
df_correlacion = pd.merge(
    races[['RACEID', 'SCORE']],
    drivers_subset,
    on='RACEID',
    how='inner'
)

# ---------------------------------------------------------
# 4. CÁLCULO DE LA MATRIZ DE CORRELACIÓN
# ---------------------------------------------------------
# Seleccionamos las columnas finales (excluyendo RACEID para que no ensucie la gráfica)
columnas_finales = [
    'SCORE',
    'DRIVER_POINTS_BEFORE_RACE',
    'POINTS',
    'POSITION_POINTS_BEFORE_RACE'
]

# Calculamos la matriz únicamente de esas variables
corr_matrix = df_correlacion[columnas_finales].corr()

# ---------------------------------------------------------
# 5. VISUALIZACIÓN (HEATMAP)
# ---------------------------------------------------------
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='RdBu_r', fmt=".2f", linewidths=0.5)

plt.title('Matriz de Correlación: Variables Seleccionadas vs SCORE')
plt.show()

# Resultado en texto para tu análisis
print("Correlación de variables con el SCORE:")
print(corr_matrix['SCORE'].sort_values(ascending=False))

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# 1. CARGA DE DATOS Y PREPARACIÓN INICIAL
# ---------------------------------------------------------
# Cargamos las bases principales (ajusta los nombres de archivo si es necesario)
races = pd.read_csv('rcs_transformed.csv', encoding='latin1')
drivers = pd.read_csv('base_final_DS33.csv')
# Se asume que existe un archivo 'PIT_STOPS.csv' para cargar los datos de pit stops.
# Si el nombre del archivo es diferente, por favor ajústalo.
ps = pd.read_csv('PIT_STOPS.csv')
# Se asume que existe un archivo 'LAP_TIMES.csv' para cargar los datos de lap times.
# Si el nombre del archivo es diferente, por favor ajústalo.
lt = pd.read_csv('LAP_TIMES.csv')

# Aseguramos que SCORE sea numérico
races['SCORE'] = pd.to_numeric(races['SCORE'], errors='coerce')

# ---------------------------------------------------------
# 2. AGREGACIONES PARA EVITAR EXPLOSIÓN DE DATOS (Métrica por Piloto/Carrera)
# ---------------------------------------------------------

# Resumen de Pit Stops (ps)
# Variables solicitadas: TOTAL_STOPS_DRIVER y STOP
ps_resumen = ps.groupby(['RACEID', 'DRIVERID']).agg({
    'TOTAL_STOPS_DRIVER': 'max',
    'STOP': 'max'
}).reset_index()

# Resumen de Lap Times (lt)
# Variables solicitadas: MILLISECONDS_CUMULATIVE, POSITION (como promedio), MILLISECONDS (como promedio)
lt_resumen = lt.groupby(['RACEID', 'DRIVERID']).agg({
    'MILLISECONDS_CUMULATIVE': 'max',
    'POSITION': 'mean',
    'MILLISECONDS': 'mean'
}).reset_index().rename(columns={
    'POSITION': 'AVG_LAP_POSITION',
    'MILLISECONDS': 'AVG_LAP_TIME'
})

# ---------------------------------------------------------
# 3. MERGING (INTEGRACIÓN TOTAL)
# ---------------------------------------------------------

# Unimos races con drivers primero (Base Combined)
df_combined = pd.merge(races[['RACEID', 'SCORE']], drivers, on='RACEID')

# Unimos con los resúmenes de ps y lt usando RACEID y DRIVERID
# Usamos 'inner' para asegurar que la correlación tenga datos completos
df_final = pd.merge(df_combined, ps_resumen, on=['RACEID', 'DRIVERID'], how='inner')
df_final = pd.merge(df_final, lt_resumen, on=['RACEID', 'DRIVERID'], how='inner')

# ---------------------------------------------------------
# 4. SELECCIÓN DE VARIABLES Y CORRELACIÓN
# ---------------------------------------------------------

# Definimos las variables que pediste para el modelo
features_interes = [
    'DRIVER_POINTS_BEFORE_RACE',
    'POINTS',
    'POSITION_POINTS_BEFORE_RACE',
    'TOTAL_STOPS_DRIVER',
    'STOP',
    'MILLISECONDS_CUMULATIVE',
    'AVG_LAP_POSITION',
    'AVG_LAP_TIME'
]

# Creamos el dataframe final para la matriz incluyendo el SCORE
# Eliminamos cualquier valor nulo que pueda romper la correlación
ds_numeric = df_final[features_interes + ['SCORE']].select_dtypes(include=['number']).dropna()

# Calcular la matriz de correlación
corr_matrix = ds_numeric.corr()

# ---------------------------------------------------------
# 5. VISUALIZACIÓN (HEATMAP)
# ---------------------------------------------------------
plt.figure(figsize=(14, 10))
sns.heatmap(corr_matrix, annot=True, cmap='RdBu_r', fmt=".2f", linewidths=0.5)
plt.title('Matriz de Correlación Final: Variables de Rendimiento vs SCORE')
plt.show()

# Imprimir el ranking de importancia para tu ensayo
print("Ranking de Correlación con respecto al SCORE:")
print(corr_matrix['SCORE'].sort_values(ascending=False))

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Cargar los datasets
races = pd.read_csv('rcs_transformed.csv', encoding='latin1')
drivers = pd.read_csv('base_final_DS33.csv')

# 2. Limpieza básica y preparación
# Convertir SCORE a numérico por si acaso
races['SCORE'] = pd.to_numeric(races['SCORE'], errors='coerce')

# 3. Merging: Unimos por RACEID
# Nota: Como queremos predecir el score de la carrera, agrupamos los datos de los pilotos
# (por ejemplo, el promedio de puntos o la diferencia mínima en el standing)
df_combined = pd.merge(races[['RACEID', 'SCORE']], drivers, on='RACEID')

# 4. Selección de variables candidatas para el modelo predictivo
features = [
  'YEAR',
  'ROUND',
  'FINAL',
  'DRIVER_POSITION_BEFORE_RACE',
  'DRIVER_POINTS_BEFORE_RACE',
  'POSITION_POINTS_BEFORE_RACE',
  'POINTS_OF_LOWER_POSITION',
  'POINTS_OF_LOWER_POSITION_BEFORE_RACE',
  'DELTA_POINTS_TO_LOWER_POSITION',
  'DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE',
  'CHANGE_DELTA_BEFORE_AND_AFTER_RACE'
]

# Calcular la matriz de correlación
corr_matrix = df_combined[features + ['SCORE']].corr()

# 5. Visualización de la Matriz de Correlación
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='RdBu_r', fmt=".2f", linewidths=0.5)
plt.title('Correlación: Variables de Pilotos vs SCORE de Carrera')
plt.show()

# 6. Mostrar variables con mayor impacto en SCORE
print("Correlación directa con la variable objetivo (SCORE):")
print(corr_matrix['SCORE'].sort_values(ascending=False))

import pandas as pd
from scipy.stats import f_oneway

# 1. Carga y preparación
rcs = pd.read_csv('rcs_transformed.csv')
drivers = pd.read_csv('base_final_DS33.csv')
df = pd.merge(rcs[['RACEID', 'SCORE']], drivers, on='RACEID')

# 2. Crear las categorías para el análisis
# Categoría de Posición: Top 3 vs Resto
df['CAT_POSICION'] = df['DRIVER_POSITION_BEFORE_RACE'].apply(
    lambda x: 'Top 3' if x <= 3 else ('Top 10' if x <= 10 else 'Otros')
)

# Categoría de Dominio: Basado en victorias
df['CAT_DOMINIO'] = pd.cut(df['WINS'], bins=[-1, 0, 3, 100], labels=['Sin Victorias', 'Pocas', 'Dominante'])

# 3. Función para ejecutar ANOVA
def ejecutar_anova(columna_categorica):
    # Agrupamos los SCORES por cada categoría
    grupos = [group['SCORE'].values for name, group in df.groupby(columna_categorica)]
    f_stat, p_val = f_oneway(*grupos)
    return f_stat, p_val

# 4. Análisis de las mejores variables
variables_anova = {
    'Posición antes de carrera': 'CAT_POSICION',
    'Dominio (Victorias)': 'CAT_DOMINIO',
    'Nombre del Piloto': 'DRIVERREF',
    'Es Final de Temporada': 'FINAL'
}

print(f"{'VARIABLE CATEGÓRICA':<30} | {'ESTADÍSTICO F':<15} | {'P-VALUE'}")
print("-" * 65)

for nombre, col in variables_anova.items():
    f, p = ejecutar_anova(col)
    print(f"{nombre:<30} | {f:<15.4f} | {p:.6f}")

"""# ANOVA"""

import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# 1. CARGA DE DATOS
races = pd.read_csv('rcs_transformed.csv', encoding='latin1')
drivers = pd.read_csv('base_final_DS33.csv')

# Asegurar que SCORE sea numérico
races['SCORE'] = pd.to_numeric(races['SCORE'], errors='coerce')

# 2. UNIR LAS BASES
df_combined = pd.merge(races[['RACEID', 'SCORE']], drivers, on='RACEID', how='inner')

# 3. CATEGORIZAR VARIABLES (Solución al ValueError)
# Usamos rank(method='first') para desempatar los ceros y forzar 3 grupos iguales
df_combined['NIVEL_PUNTOS_PREVIO'] = pd.qcut(
    df_combined['DRIVER_POINTS_BEFORE_RACE'].rank(method='first'),
    q=3,
    labels=["Bajo", "Medio", "Alto"]
)

df_combined['NIVEL_POSICION_PREVIO'] = pd.qcut(
    df_combined['POSITION_POINTS_BEFORE_RACE'].rank(method='first'),
    q=3,
    labels=["Top", "Mitad", "Fondo"]
)

# 4. EJECUTAR EL ANOVA
# Analizamos si el SCORE varía según estos niveles
modelo = ols('SCORE ~ C(NIVEL_PUNTOS_PREVIO) + C(NIVEL_POSICION_PREVIO)', data=df_combined).fit()
anova_table = sm.stats.anova_lm(modelo, typ=2)

# 5. RESULTADOS
print("--- TABLA ANOVA (SIGNIFICANCIA ESTADÍSTICA) ---")
print(anova_table)

# Extraer P-Values para interpretación fácil
p_puntos = anova_table.loc['C(NIVEL_PUNTOS_PREVIO)', 'PR(>F)']
p_posicion = anova_table.loc['C(NIVEL_POSICION_PREVIO)', 'PR(>F)']

print("\n--- INTERPRETACIÓN PARA TU MODELO ---")
if p_puntos < 0.05:
    print(f"✅ NIVEL_PUNTOS_PREVIO es SIGNIFICATIVA (P-Value: {p_puntos:.4f}). ¡Úsala en tu modelo!")
else:
    print(f"❌ NIVEL_PUNTOS_PREVIO no es significativa.")

if p_posicion < 0.05:
    print(f"✅ NIVEL_POSICION_PREVIO es SIGNIFICATIVA (P-Value: {p_posicion:.4f}). ¡Úsala en tu modelo!")
else:
    print(f"❌ NIVEL_POSICION_PREVIO no es significativa.")

# 6. VER PROMEDIOS (Para justificar en tu ensayo)
print("\n--- RENDIMIENTO (SCORE) PROMEDIO POR GRUPO ---")
print(df_combined.groupby('NIVEL_PUNTOS_PREVIO', observed=True)['SCORE'].mean())

import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
import warnings
warnings.filterwarnings('ignore')

# 1. Preparación del DataFrame Maestro
# Cargamos rcs_transformed para obtener el SCORE
rs = pd.read_csv('rcs_transformed.csv', encoding='latin1')
# Cargamos base_final_DS33 que contiene tus variables de Driver Standings
drivers = pd.read_csv('base_final_DS33.csv')

# Unimos por RACEID para tener el SCORE alineado con los datos del piloto
# Asegúrate de que los nombres de las columnas coincidan (RACEID vs raceId)
df_anova_master = pd.merge(drivers, rs[['RACEID', 'SCORE']], on='RACEID', how='inner')

print("="*70)
print(" ANÁLISIS ANOVA: VARIABLES DE DRIVER STANDINGS VS SCORE ")
print("="*70)

# Lista de variables de base_final_DS33 que quieres probar
# He incluido las que mencionaste: puntos acumulados, posición y deltas
variables_for_anova = [
    'DRIVER_POINTS_BEFORE_RACE',
    'POSITION_POINTS_BEFORE_RACE',
    'POINTS',
    'POINTS_OF_LOWER_POSITION_BEFORE_RACE',
    'DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE'
]

anova_summary = []

for var in variables_for_anova:
    if var not in df_anova_master.columns:
        print(f" Variable {var} no encontrada en el dataset.")
        continue

    # Limpieza de datos y asegurarnos que SCORE sea numérico
    temp_df = df_anova_master[[var, 'SCORE']].dropna()
    temp_df['SCORE'] = pd.to_numeric(temp_df['SCORE'], errors='coerce')
    temp_df = temp_df.dropna()

    # Lógica de Categorización (Discretización)
    categorical_name = var + '_CAT'

    # Usamos rank para evitar el error de duplicados en qcut (común en puntos de F1)
    if temp_df[var].nunique() > 5:
        try:
            temp_df[categorical_name] = pd.qcut(
                temp_df[var].rank(method='first'),
                q=4,
                labels=['Bajo/Fondo', 'Medio-Bajo', 'Medio-Alto', 'Alto/Top']
            )
        except:
            temp_df[categorical_name] = temp_df[var].astype('category')
    else:
        temp_df[categorical_name] = temp_df[var].astype('category')

    # Ejecución del ANOVA
    try:
        formula = f'SCORE ~ C({categorical_name})'
        model = ols(formula, data=temp_df).fit()
        anova_table = sm.stats.anova_lm(model, typ=2)

        p_value = anova_table['PR(>F)'][0]
        f_stat = anova_table['F'][0]

        significativo = "SÍ" if p_value < 0.05 else "NO"

        print(f" Variable: {var:35} | P-Value: {p_value:.4e} | Significativo: {significativo}")

        anova_summary.append({
            'Variable': var,
            'Estadístico_F': f_stat,
            'P_Value': p_value,
            'Es_Significativa': significativo
        })
    except Exception as e:
        print(f" Error en {var}: {e}")

# 2. Resumen Final
print("\n" + "="*70)
print(" RESULTADOS ORDENADOS POR IMPORTANCIA (Estadístico F) ")
print("="*70)
resumen_df = pd.DataFrame(anova_summary).sort_values(by='Estadístico_F', ascending=False)
print(resumen_df.to_string(index=False))

"""# RANDOM FORREST"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Re-load races and drivers as they are needed for df_final in this cell context
races = pd.read_csv('rcs_transformed.csv', encoding='latin1')
drivers = pd.read_csv('base_final_DS33.csv')

# Ensure SCORE is numeric
races['SCORE'] = pd.to_numeric(races['SCORE'], errors='coerce')

# 1. PREPARACIÓN DE LA DATA
# Create df_final by merging rcs_transformed (as races) and drivers.
# The original df_final also included 'ps' and 'lt' data, but those files were not found.
# We will proceed with available data and exclude features from 'ps' and 'lt'.
df_final = pd.merge(races[['RACEID', 'SCORE']], drivers, on='RACEID', how='inner')

# Definimos las variables candidatas basándonos en tus análisis previos
# Features 'TOTAL_STOPS_DRIVER', 'AVG_LAP_TIME', 'AVG_LAP_POSITION' are removed
# because their source files (PIT_STOPS.csv, LAP_TIMES.csv) were not found.
features = [
    'DRIVER_POINTS_BEFORE_RACE',
    'POSITION_POINTS_BEFORE_RACE',
    'POINTS',
    'POINTS_OF_LOWER_POSITION_BEFORE_RACE',
    'DELTA_POINTS_TO_LOWER_POSITION_BEFORE_RACE'
]

# Limpieza final: quitar nulos y asegurar que todo sea numérico
df_rf = df_final[features + ['SCORE']].dropna()
X = df_rf[features]
y = df_rf['SCORE']

# 2. ENTRENAMIENTO DEL MODELO
# Dividimos en entrenamiento y prueba (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializamos el Random Forest para Regresión
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# 3. EXTRACCIÓN DE IMPORTANCIA DE VARIABLES
importances = rf_model.feature_importances_
feature_importance_df = pd.DataFrame({
    'Variable': features,
    'Importancia': importances
}).sort_values(by='Importancia', ascending=False)

# 4. VISUALIZACIÓN
plt.figure(figsize=(12, 8))
sns.barplot(x='Importancia', y='Variable', data=feature_importance_df, palette='viridis')
plt.title('Importancia de Variables (Random Forest) para predecir SCORE')
plt.xlabel('Poder Predictivo (0 a 1)')
plt.ylabel('Variables de F1')
plt.show()

# 5. CONCLUSIÓN TÉCNICA
print("--- VARIABLES SELECCIONADAS POR EL MODELO ---")
print(feature_importance_df)