# -*- coding: utf-8 -*-
"""Estructura_LT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebKcQUSW-WpOOhegl52vD0m-kMTTWFPe

# 1. CARGA
"""

!pip install ipywidgets scikit-learn xgboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

from sklearn.preprocessing import StandardScaler, MinMaxScaler


from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.neural_network import MLPRegressor # MLP = multi layer perceptron
from sklearn.svm import SVR

pd.set_option('display.max_columns', None)
lap_times = pd.read_csv('LAP_TIMES.csv')
lap_times.head()

"""#2. EXPLORACIÓN"""

print("Info for Lap Times DataFrame:")
lap_times.info()
print("\nDescriptive statistics for Lap Times DataFrame:")
lap_times.describe()

print("Missing values in Lap Times DataFrame:")
lap_times.isnull().sum()

"""#3. LIMPIEZA"""

lap_times["PIT_BINARY"] = lap_times["PIT_STOP"].apply(lambda x: 1 if x == 'Y' else 0)

# Get current columns
cols = lap_times.columns.tolist()

# Find the index of 'PIT_STOP'
pit_stop_idx = cols.index('PIT_STOP')

# Remove 'PIT_BINARY' from its current position (if it exists) and insert it after 'PIT_STOP'
if 'PIT_BINARY' in cols:
    cols.remove('PIT_BINARY')

cols.insert(pit_stop_idx + 1, 'PIT_BINARY')

# Reassign the DataFrame with the new column order
lap_times = lap_times[cols]

lap_times

lap_times = lap_times.sort_values(by=['DRIVERID', 'RACEID', 'LAP']).reset_index(drop=True)

lap_times

lap_times['DRIVERREF'] = lap_times['DRIVERREF'].apply(lambda x: x.split('_', 1)[-1] if isinstance(x, str) and '_' in x else x)
lap_times.head()

lap_times['MILLISECONDS_CUMULATIVE'] = lap_times.groupby(['DRIVERID', 'RACEID'])['MILLISECONDS'].cumsum()

lap_times

"""#4. CONVERSIÓN DE TIPOS"""

lap_times["POSITION"] = pd.to_numeric(lap_times["POSITION"], errors="coerce")

lap_times["MILLISECONDS"] = pd.to_numeric(lap_times["MILLISECONDS"], errors="coerce")

"""#5. FEATURE ENGINEERING"""

# Diferencia de ritmo
lap_times["PACE_DIFF"] = lap_times["MILLISECONDS_CUMULATIVE"] - lap_times["MEDIAN_MILLISECONDS_CUMULATIVE"]

# Cambio de posición por vuelta
lap_times["POSITION_CHANGE"] = lap_times.groupby(["RACEID","DRIVERID"])["POSITION"].diff()

lap_times

lap_times.info()

lap_times.isnull().sum()

lap_times

lt_mod = lap_times[['RACEID','MILLISECONDS_CUMULATIVE', 'POSITION', 'MILLISECONDS']]
lt_mod.head()

lt_mod.to_csv('lt_mod.csv', index=False)
print('DataFrame guardado como lap_times_mod.csv')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import pearsonr, spearmanr
import warnings
warnings.filterwarnings('ignore')

# Configuración profesional para visualizaciones
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (14, 10)
plt.rcParams['font.size'] = 11
plt.rcParams['axes.titlesize'] = 13
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['figure.dpi'] = 150

print("="*80)
print(" ANÁLISIS DE CORRELACIÓN: lap_times_final1 → score")
print("="*80)

# ============================================================================
# 1. CARGAR Y PREPARAR DATOS
# ============================================================================

# Cargar tabla de scores
rcs_df = pd.read_csv('rcs_transformed.csv')
print(f"\n✓ rcs_transformed.csv cargado: {rcs_df.shape}")

# Asegurar columna 'score'
if 'SCORE' in rcs_df.columns:
    rcs_df.rename(columns={'SCORE': 'score'}, inplace=True)
    print("  - Columna 'SCORE' renombrada a 'score'")

# Verificar que lap_times_final1 existe (debe estar en memoria)
if 'lap_times_final1' not in locals():
    print("\n✗ Error: lap_times_final1 no está cargado en memoria")
    print("  Por favor, asegúrate de que la variable 'lap_times_final1' existe")
    exit()

print(f"\n✓ lap_times_final1 cargado: {lap_times_final1.shape}")

# ============================================================================
# 2. FUSIONAR DATOS
# ============================================================================

# Determinar columnas de fusión
merge_cols = ['RACEID', 'DRIVERID'] if 'DRIVERID' in rcs_df.columns else ['RACEID']

print(f"\n✓ Fusionando datos usando: {merge_cols}")
merged_df = pd.merge(lap_times_final1, rcs_df, on=merge_cols, how='inner')
print(f"  - Registros originales lap_times: {len(lap_times_final1):,}")
print(f"  - Registros después de fusión: {len(merged_df):,}")

if len(merged_df) == 0:
    print("\n✗ Error: No hay datos después de la fusión")
    exit()

# ============================================================================
# 3. SELECCIONAR VARIABLES PARA CORRELACIÓN
# ============================================================================

# Variables a analizar (basado en lógica de negocio)
variables_to_analyze = [
    'LAP',                    # Número de vuelta
    'POSITION',               # Posición en vuelta
    'MILLISECONDS',           # Tiempo de vuelta
    'PIT_BINARY',             # Parada en boxes
    'MILLISECONDS_CUMULATIVE', # Tiempo acumulado
    'MEDIAN_MILLISECONDS_CUMULATIVE', # Mediana de referencia
    'PACE_DIFF',              # Diferencia de ritmo
    'POSITION_CHANGE',        # Cambio de posición
    'score'                   # Variable objetivo
]

# Filtrar variables que existen
available_vars = [var for var in variables_to_analyze if var in merged_df.columns]
missing_vars = [var for var in variables_to_analyze if var not in merged_df.columns]

print(f"\n✓ Variables disponibles: {available_vars}")
if missing_vars:
    print(f"  ⚠️ Variables no encontradas: {missing_vars}")

# Crear DataFrame para correlación
df_corr = merged_df[available_vars].copy()
print(f"\n✓ DataFrame para correlación: {df_corr.shape}")

# ============================================================================
# 4. LIMPIEZA Y PREPARACIÓN DE DATOS
# ============================================================================

print("\n" + "="*80)
print(" LIMPIEZA DE DATOS")
print("="*80)

# Estadísticas iniciales
print(f"\nRegistros iniciales: {len(df_corr):,}")
print(f"NaN por variable:")
for col in df_corr.columns:
    nan_count = df_corr[col].isna().sum()
    if nan_count > 0:
        print(f"  - {col}: {nan_count:,} ({nan_count/len(df_corr)*100:.1f}%)")

# Eliminar filas con NaN
df_corr_clean = df_corr.dropna()
print(f"\nRegistros después de eliminar NaN: {len(df_corr_clean):,}")
print(f"Registros perdidos: {len(df_corr) - len(df_corr_clean):,}")

if len(df_corr_clean) < 100:
    print("\n✗ Error: Datos insuficientes después de limpieza")
    exit()

# Winsorización para reducir impacto de outliers (opcional pero recomendado)
print("\n✓ Aplicando winsorización al 1% y 99% para reducir outliers...")
for col in df_corr_clean.columns:
    if col != 'PIT_BINARY' and col != 'score':  # No winsorizar binarias ni objetivo
        df_corr_clean[col] = stats.mstats.winsorize(df_corr_clean[col], limits=[0.01, 0.01])

# ============================================================================
# 5. CALCULAR CORRELACIONES
# ============================================================================

print("\n" + "="*80)
print(" CÁLCULO DE CORRELACIONES")
print("="*80)

# Matriz de correlación Pearson
corr_matrix_pearson = df_corr_clean.corr(method='pearson')

# Matriz de correlación Spearman (robusto a outliers)
corr_matrix_spearman = df_corr_clean.corr(method='spearman')

# Extraer correlaciones con score
corr_with_score_pearson = corr_matrix_pearson['score'].drop('score').sort_values(ascending=False)
corr_with_score_spearman = corr_matrix_spearman['score'].drop('score').sort_values(ascending=False)

# Calcular p-values para significancia estadística
p_values = {}
for col in df_corr_clean.columns:
    if col != 'score':
        mask = ~(df_corr_clean[col].isna() | df_corr_clean['score'].isna())
        if mask.sum() > 0:
            _, p_val = pearsonr(df_corr_clean.loc[mask, col], df_corr_clean.loc[mask, 'score'])
            p_values[col] = p_val

# Mostrar resultados
print("\n📊 CORRELACIÓN DE PEARSON (lineal):")
print("-" * 50)
for var, corr in corr_with_score_pearson.items():
    significance = "***" if p_values.get(var, 1) < 0.001 else "**" if p_values.get(var, 1) < 0.01 else "*" if p_values.get(var, 1) < 0.05 else ""
    direction = "POSITIVA" if corr > 0 else "NEGATIVA"
    strength = "FUERTE" if abs(corr) >= 0.5 else "MEDIA" if abs(corr) >= 0.3 else "DÉBIL"
    print(f"  {var:30s} {corr:8.3f} {direction:8s} {strength:5s} {significance}")

print("\n📊 CORRELACIÓN DE SPEARMAN (no-lineal, robusta):")
print("-" * 50)
for var, corr in corr_with_score_spearman.items():
    strength = "FUERTE" if abs(corr) >= 0.5 else "MEDIA" if abs(corr) >= 0.3 else "DÉBIL"
    print(f"  {var:30s} {corr:8.3f} ({strength})")

# ============================================================================
# 6. CLASIFICACIÓN DE VARIABLES
# ============================================================================

print("\n" + "="*80)
print(" CLASIFICACIÓN POR POTENCIAL PREDICTIVO")
print("="*80)

# Definir umbrales
high_threshold = 0.5
medium_threshold = 0.3

high_corr_vars = corr_with_score_pearson[abs(corr_with_score_pearson) >= high_threshold]
medium_corr_vars = corr_with_score_pearson[(abs(corr_with_score_pearson) >= medium_threshold) &
                                            (abs(corr_with_score_pearson) < high_threshold)]
low_corr_vars = corr_with_score_pearson[abs(corr_with_score_pearson) < medium_threshold]

print(f"\n📈 ALTA RELACIÓN POTENCIAL (|r| ≥ {high_threshold}):")
if len(high_corr_vars) > 0:
    for var, corr in high_corr_vars.items():
        print(f"  ✅ {var}: {corr:.3f}")
else:
    print("  Ninguna variable alcanzó este umbral")

print(f"\n📊 RELACIÓN MEDIA ({medium_threshold} ≤ |r| < {high_threshold}):")
if len(medium_corr_vars) > 0:
    for var, corr in medium_corr_vars.items():
        print(f"  📌 {var}: {corr:.3f}")
else:
    print("  Ninguna variable en este rango")

print(f"\n📉 RELACIÓN DÉBIL O IRRELEVANTE (|r| < {medium_threshold}):")
if len(low_corr_vars) > 0:
    for var, corr in low_corr_vars.items():
        print(f"  ⚠️ {var}: {corr:.3f}")
else:
    print("  Ninguna variable en este rango")

# ============================================================================
# 7. MAPAS DE CORRELACIÓN (VISUALIZACIONES)
# ============================================================================

print("\n" + "="*80)
print(" GENERANDO VISUALIZACIONES")
print("="*80)

# 7.1 Mapa de calor principal (Pearson con máscara triangular)
fig, axes = plt.subplots(2, 2, figsize=(16, 14))

# Mapa 1: Triangular superior
mask = np.triu(np.ones_like(corr_matrix_pearson, dtype=bool))
sns.heatmap(corr_matrix_pearson,
            mask=mask,
            annot=True,
            fmt='.2f',
            cmap='RdBu_r',
            center=0,
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8, "label": "Correlación de Pearson"},
            ax=axes[0, 0],
            annot_kws={"size": 9})
axes[0, 0].set_title('Matriz de Correlación (Pearson) - Triangular Superior', fontsize=12, fontweight='bold')

# Mapa 2: Completo
sns.heatmap(corr_matrix_pearson,
            annot=True,
            fmt='.2f',
            cmap='coolwarm',
            center=0,
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8, "label": "Correlación de Pearson"},
            ax=axes[0, 1],
            annot_kws={"size": 9})
axes[0, 1].set_title('Matriz de Correlación Completa (Pearson)', fontsize=12, fontweight='bold')

# Mapa 3: Spearman
sns.heatmap(corr_matrix_spearman,
            annot=True,
            fmt='.2f',
            cmap='viridis',
            center=0,
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8, "label": "Correlación de Spearman"},
            ax=axes[1, 0],
            annot_kws={"size": 9})
axes[1, 0].set_title('Matriz de Correlación (Spearman) - Robusto a outliers', fontsize=12, fontweight='bold')

# Mapa 4: Solo correlaciones con score (formato compacto)
corr_with_score_matrix = pd.DataFrame(corr_with_score_pearson).T
sns.heatmap(corr_with_score_matrix,
            annot=True,
            fmt='.3f',
            cmap='RdBu_r',
            center=0,
            cbar_kws={"shrink": 0.8, "label": "Correlación con Score"},
            ax=axes[1, 1],
            annot_kws={"size": 10})
axes[1, 1].set_title('Correlación de cada variable con Score', fontsize=12, fontweight='bold')
axes[1, 1].set_ylabel('')

plt.suptitle('ANÁLISIS DE CORRELACIÓN: lap_times_final1 → score', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('matriz_correlacion_completa.png', dpi=300, bbox_inches='tight')
plt.show()

# 7.2 Gráfico de barras de correlaciones
fig, ax = plt.subplots(figsize=(12, 8))

# Crear barras horizontales
colors = ['#2ecc71' if x > 0 else '#e74c3c' for x in corr_with_score_pearson.values]
bars = ax.barh(range(len(corr_with_score_pearson)), corr_with_score_pearson.values, color=colors, alpha=0.8)

# Personalizar
ax.set_yticks(range(len(corr_with_score_pearson)))
ax.set_yticklabels(corr_with_score_pearson.index)
ax.set_xlabel('Correlación con Score', fontsize=12, fontweight='bold')
ax.set_title('Correlación de Pearson: Variables de lap_times vs Score', fontsize=13, fontweight='bold')
ax.axvline(x=0, color='black', linestyle='-', linewidth=0.8)
ax.axvline(x=0.3, color='orange', linestyle='--', alpha=0.5, label='|r| = 0.3 (mínimo relevante)')
ax.axvline(x=-0.3, color='orange', linestyle='--', alpha=0.5)
ax.axvline(x=0.5, color='green', linestyle='--', alpha=0.5, label='|r| = 0.5 (fuerte)')
ax.axvline(x=-0.5, color='green', linestyle='--', alpha=0.5)
ax.legend(loc='lower right')

# Añadir valores
for i, (bar, val) in enumerate(zip(bars, corr_with_score_pearson.values)):
    ax.text(val + (0.02 if val > 0 else -0.08), i, f'{val:.3f}',
            va='center', fontsize=10, fontweight='bold')

plt.grid(True, alpha=0.3, axis='x')
plt.tight_layout()
plt.savefig('barras_correlacion_score.png', dpi=300, bbox_inches='tight')
plt.show()

# 7.3 Scatter plots para las 4 variables más correlacionadas
top_vars = corr_with_score_pearson.abs().nlargest(4).index.tolist()

fig, axes = plt.subplots(2, 2, figsize=(14, 12))
axes = axes.flatten()

for idx, var in enumerate(top_vars):
    if idx < 4:
        # Sample para mejor visualización
        sample_size = min(3000, len(df_corr_clean))
        df_sample = df_corr_clean.sample(n=sample_size, random_state=42)

        # Scatter plot
        axes[idx].scatter(df_sample[var], df_sample['score'],
                         alpha=0.5, s=20, c=df_sample['score'],
                         cmap='viridis', edgecolors='black', linewidth=0.3)

        # Línea de regresión
        z = np.polyfit(df_sample[var], df_sample['score'], 1)
        p = np.poly1d(z)
        axes[idx].plot(df_sample[var].sort_values(),
                      p(df_sample[var].sort_values()),
                      "r-", linewidth=2, label=f'Tendencia (r={corr_with_score_pearson[var]:.3f})')

        # Personalizar
        axes[idx].set_xlabel(var, fontsize=11, fontweight='bold')
        axes[idx].set_ylabel('Score', fontsize=11, fontweight='bold')

        # Interpretación automática
        if var == 'MILLISECONDS_CUMULATIVE':
            axes[idx].set_title(f'Relación: {var} vs Score\nMenor tiempo acumulado → Mayor score', fontsize=11)
        elif var == 'POSITION':
            axes[idx].set_title(f'Relación: {var} vs Score\nMejor posición → Mayor score', fontsize=11)
        elif var == 'PACE_DIFF':
            axes[idx].set_title(f'Relación: {var} vs Score\nRitmo más rápido (negativo) → Mayor score', fontsize=11)
        else:
            axes[idx].set_title(f'{var} vs Score | r = {corr_with_score_pearson[var]:.3f}', fontsize=11)

        axes[idx].legend()
        axes[idx].grid(True, alpha=0.3)

plt.suptitle('Relaciones Clave: Variables más correlacionadas con Score', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('scatter_plots_top_variables.png', dpi=300, bbox_inches='tight')
plt.show()

# 7.4 Mapa de calor con significancia estadística
fig, ax = plt.subplots(figsize=(12, 10))

# Crear máscara para mostrar solo correlaciones significativas (p < 0.05)
significance_mask = np.zeros_like(corr_matrix_pearson, dtype=bool)
for i in range(len(corr_matrix_pearson.columns)):
    for j in range(len(corr_matrix_pearson.columns)):
        if i != j:
            col_i = corr_matrix_pearson.columns[i]
            col_j = corr_matrix_pearson.columns[j]
            _, p_val = pearsonr(df_corr_clean[col_i], df_corr_clean[col_j])
            if p_val > 0.05:
                significance_mask[i, j] = True

# Aplicar máscara
corr_masked = corr_matrix_pearson.mask(significance_mask)

sns.heatmap(corr_masked,
            annot=True,
            fmt='.2f',
            cmap='RdBu_r',
            center=0,
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8, "label": "Correlación (solo significativa)"},
            ax=ax,
            annot_kws={"size": 10})

ax.set_title('Matriz de Correlación - Solo valores estadísticamente significativos (p < 0.05)',
             fontsize=13, fontweight='bold')

plt.tight_layout()
plt.savefig('correlacion_significativa.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# 8. REPORTE FINAL Y RECOMENDACIONES
# ============================================================================

print("\n" + "="*80)
print(" REPORTE FINAL Y RECOMENDACIONES PARA MODELADO")
print("="*80)

print("\n✅ TOP 3 VARIABLES MÁS PREDICTIVAS:")
for i, (var, corr) in enumerate(corr_with_score_pearson.abs().nlargest(3).items(), 1):
    actual_corr = corr_with_score_pearson[var]
    print(f"\n  {i}. {var}")
    print(f"     Correlación: {actual_corr:.3f}")
    if var == 'MILLISECONDS_CUMULATIVE':
        print(f"     Interpretación: Por cada 1000ms de mejora en tiempo acumulado, el score aumenta significativamente")
    elif var == 'POSITION':
        print(f"     Interpretación: Mejorar 1 posición incrementa el score en proporción directa")
    elif var == 'PACE_DIFF':
        print(f"     Interpretación: Ser 0.1s más rápido que la referencia por vuelta mejora el score")

print("\n📋 RECOMENDACIONES PARA MODELADO PREDICTIVO:")
print("""
  1. VARIABLES A INCLUIR SÍ O SÍ (base del modelo):
     - MILLISECONDS_CUMULATIVE (o su valor final por carrera)
     - POSITION (especialmente posición final)
     - PACE_DIFF (mejor feature ingenierizada)

  2. VARIABLES COMPLEMENTARIAS (para mejorar precisión):
     - POSITION_CHANGE (captura dinámica de carrera)
     - PIT_BINARY (convertir a PIT_COUNT por carrera)
     - MILLISECONDS (promedio por carrera, no por vuelta)

  3. FEATURES A INGENIERIZAR:
     - Tiempo total de carrera (max MILLISECONDS_CUMULATIVE)
     - Posición promedio por carrera
     - Consistencia (std de MILLISECONDS)
     - Número de adelantamientos (suma POSITION_CHANGE positivos)

  4. PRECAUCIONES:
     - Agregar por carrera (no usar datos por vuelta directamente)
     - Verificar multicolinealidad entre MILLISECONDS_CUMULATIVE y POSITION
     - Considerar efectos de interacción (ej: PIT_BINARY * PACE_DIFF)
""")

print("\n" + "="*80)
print(" ANÁLISIS COMPLETADO")
print("="*80)
print("\n✓ Visualizaciones guardadas:")
print("  - matriz_correlacion_completa.png")
print("  - barras_correlacion_score.png")
print("  - scatter_plots_top_variables.png")
print("  - correlacion_significativa.png")



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Configuración de estilo para gráficos profesionales
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 10)
plt.rcParams['font.size'] = 12
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12

def crear_mapa_correlacion_completo(merged_df, output_prefix='correlation_map'):
    """
    Crea múltiples visualizaciones de correlación

    Parámetros:
    - merged_df: DataFrame con los datos fusionados (debe incluir 'score')
    - output_prefix: Prefijo para guardar las imágenes
    """

    # 1. Seleccionar variables numéricas relevantes
    variables_interest = [
        'LAP', 'POSITION', 'MILLISECONDS', 'PIT_BINARY',
        'MILLISECONDS_CUMULATIVE', 'MEDIAN_MILLISECONDS_CUMULATIVE',
        'PACE_DIFF', 'POSITION_CHANGE', 'score'
    ]

    # Filtrar variables que existen en el DataFrame
    available_vars = [var for var in variables_interest if var in merged_df.columns]

    print(f"✓ Variables disponibles para correlación: {available_vars}")

    # Preparar datos
    df_corr = merged_df[available_vars].copy()

    # Manejar outliers con winsorización
    for col in df_corr.columns:
        if df_corr[col].dtype in ['float64', 'int64'] and col != 'PIT_BINARY':
            df_corr[col] = stats.mstats.winsorize(df_corr[col], limits=[0.01, 0.01])

    # Eliminar NaN
    df_corr = df_corr.dropna()
    print(f"✓ Datos para correlación: {len(df_corr):,} registros")

    # Calcular matriz de correlación
    corr_matrix = df_corr.corr(method='pearson')
    corr_matrix_spearman = df_corr.corr(method='spearman')

    # 1. MAPA DE CALOR CON MÁSCARA TRIANGULAR SUPERIOR
    fig, axes = plt.subplots(2, 2, figsize=(16, 14))

    # 1.1 Heatmap triangular (Pearson)
    mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
    sns.heatmap(corr_matrix,
                mask=mask,
                annot=True,
                fmt='.2f',
                cmap='RdBu_r',
                center=0,
                square=True,
                linewidths=0.5,
                cbar_kws={"shrink": 0.8, "label": "Correlación de Pearson"},
                ax=axes[0, 0])
    axes[0, 0].set_title('Matriz de Correlación (Pearson)\nTriangular Superior', fontsize=14, fontweight='bold')

    # 1.2 Heatmap completo (Pearson)
    sns.heatmap(corr_matrix,
                annot=True,
                fmt='.2f',
                cmap='coolwarm',
                center=0,
                square=True,
                linewidths=0.5,
                cbar_kws={"shrink": 0.8, "label": "Correlación de Pearson"},
                ax=axes[0, 1])
    axes[0, 1].set_title('Matriz de Correlación Completa (Pearson)', fontsize=14, fontweight='bold')

    # 1.3 Heatmap Spearman
    mask = np.triu(np.ones_like(corr_matrix_spearman, dtype=bool))
    sns.heatmap(corr_matrix_spearman,
                mask=mask,
                annot=True,
                fmt='.2f',
                cmap='viridis',
                center=0,
                square=True,
                linewidths=0.5,
                cbar_kws={"shrink": 0.8, "label": "Correlación de Spearman"},
                ax=axes[1, 0])
    axes[1, 0].set_title('Matriz de Correlación (Spearman)\nRelaciones no-lineales', fontsize=14, fontweight='bold')

    # 1.4 Cluster map (dendrograma)
    from scipy.cluster.hierarchy import dendrogram, linkage
    from scipy.spatial.distance import squareform

    # Calcular linkage para clustering
    distance_matrix = 1 - abs(corr_matrix)
    condensed_distances = squareform(distance_matrix)
    linkage_matrix = linkage(condensed_distances, method='average')

    # Crear heatmap con clustering
    sns.clustermap(corr_matrix,
                   annot=True,
                   fmt='.2f',
                   cmap='RdBu_r',
                   center=0,
                   square=True,
                   linewidths=0.5,
                   figsize=(12, 10),
                   dendrogram_ratio=0.2,
                   cbar_pos=(0.02, 0.76, 0.03, 0.2))
    plt.suptitle('Clustering de Variables por Correlación', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()

    plt.tight_layout()
    plt.savefig(f'{output_prefix}_matrices_completas.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 2. GRÁFICO DE BARRAS: CORRELACIONES CON SCORE
    fig, axes = plt.subplots(1, 2, figsize=(14, 8))

    # Extraer correlaciones con score
    corr_with_score = corr_matrix['score'].drop('score').sort_values(ascending=False)
    corr_with_score_spearman = corr_matrix_spearman['score'].drop('score').sort_values(ascending=False)

    # Colores basados en positivo/negativo
    colors_pearson = ['#2ecc71' if x > 0 else '#e74c3c' for x in corr_with_score.values]
    colors_spearman = ['#2ecc71' if x > 0 else '#e74c3c' for x in corr_with_score_spearman.values]

    # Gráfico de barras Pearson
    bars1 = axes[0].barh(range(len(corr_with_score)), corr_with_score.values, color=colors_pearson)
    axes[0].set_yticks(range(len(corr_with_score)))
    axes[0].set_yticklabels(corr_with_score.index)
    axes[0].set_xlabel('Correlación con Score', fontsize=12, fontweight='bold')
    axes[0].set_title('Correlación de Pearson con Score\n(ordenado por magnitud)', fontsize=13, fontweight='bold')
    axes[0].axvline(x=0, color='black', linestyle='-', linewidth=0.8)
    axes[0].axvline(x=0.2, color='gray', linestyle='--', alpha=0.5, label='|r|=0.2')
    axes[0].axvline(x=-0.2, color='gray', linestyle='--', alpha=0.5)
    axes[0].axvline(x=0.5, color='green', linestyle='--', alpha=0.5, label='|r|=0.5')
    axes[0].axvline(x=-0.5, color='green', linestyle='--', alpha=0.5)
    axes[0].legend()

    # Añadir valores en las barras
    for i, (bar, val) in enumerate(zip(bars1, corr_with_score.values)):
        axes[0].text(val + (0.02 if val > 0 else -0.08), i, f'{val:.3f}',
                    va='center', fontsize=10, fontweight='bold')

    # Gráfico de barras Spearman
    bars2 = axes[1].barh(range(len(corr_with_score_spearman)), corr_with_score_spearman.values, color=colors_spearman)
    axes[1].set_yticks(range(len(corr_with_score_spearman)))
    axes[1].set_yticklabels(corr_with_score_spearman.index)
    axes[1].set_xlabel('Correlación con Score', fontsize=12, fontweight='bold')
    axes[1].set_title('Correlación de Spearman con Score\n(robusto a outliers)', fontsize=13, fontweight='bold')
    axes[1].axvline(x=0, color='black', linestyle='-', linewidth=0.8)
    axes[1].axvline(x=0.2, color='gray', linestyle='--', alpha=0.5)
    axes[1].axvline(x=-0.2, color='gray', linestyle='--', alpha=0.5)
    axes[1].axvline(x=0.5, color='green', linestyle='--', alpha=0.5)
    axes[1].axvline(x=-0.5, color='green', linestyle='--', alpha=0.5)

    for i, (bar, val) in enumerate(zip(bars2, corr_with_score_spearman.values)):
        axes[1].text(val + (0.02 if val > 0 else -0.08), i, f'{val:.3f}',
                    va='center', fontsize=10, fontweight='bold')

    plt.tight_layout()
    plt.savefig(f'{output_prefix}_correlaciones_con_score.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 3. SCATTER PLOTS: Relaciones clave con score
    top_vars = corr_with_score.abs().nlargest(4).index.tolist()

    fig, axes = plt.subplots(2, 2, figsize=(14, 12))
    axes = axes.flatten()

    for idx, var in enumerate(top_vars):
        if idx < 4:
            # Sample para mejor visualización (máx 5000 puntos)
            sample_size = min(5000, len(df_corr))
            df_sample = df_corr.sample(n=sample_size, random_state=42)

            # Scatter plot con línea de tendencia
            axes[idx].scatter(df_sample[var], df_sample['score'],
                            alpha=0.5, s=30, c=df_sample['score'],
                            cmap='viridis', edgecolors='black', linewidth=0.5)

            # Línea de regresión
            z = np.polyfit(df_sample[var], df_sample['score'], 1)
            p = np.poly1d(z)
            axes[idx].plot(df_sample[var].sort_values(),
                          p(df_sample[var].sort_values()),
                          "r-", linewidth=2, label=f'Tendencia (r={corr_with_score[var]:.3f})')

            axes[idx].set_xlabel(var, fontsize=11, fontweight='bold')
            axes[idx].set_ylabel('Score', fontsize=11, fontweight='bold')
            axes[idx].set_title(f'Relación entre {var} y Score\nCorrelación: {corr_with_score[var]:.3f}',
                               fontsize=12, fontweight='bold')
            axes[idx].legend()
            axes[idx].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(f'{output_prefix}_scatter_plots.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 4. HEATMAP DE SIGNIFICANCIA ESTADÍSTICA
    # Calcular p-values
    from scipy.stats import pearsonr

    p_values = pd.DataFrame(np.ones_like(corr_matrix),
                           index=corr_matrix.index,
                           columns=corr_matrix.columns)

    for i in range(len(df_corr.columns)):
        for j in range(len(df_corr.columns)):
            if i != j:
                _, p_val = pearsonr(df_corr.iloc[:, i], df_corr.iloc[:, j])
                p_values.iloc[i, j] = p_val

    fig, ax = plt.subplots(figsize=(12, 10))

    # Crear máscara para significancia
    significance = p_values.copy()
    significance[significance > 0.05] = 0  # No significativo
    significance[significance <= 0.05] = 1  # Significativo
    significance[significance == 0] = np.nan

    # Heatmap con significancia marcada
    sns.heatmap(corr_matrix,
                annot=True,
                fmt='.2f',
                cmap='coolwarm',
                center=0,
                square=True,
                linewidths=0.5,
                cbar_kws={"shrink": 0.8, "label": "Correlación"},
                ax=ax)

    # Añadir asteriscos para correlaciones significativas
    for i in range(len(corr_matrix.columns)):
        for j in range(len(corr_matrix.columns)):
            if p_values.iloc[i, j] <= 0.05:
                ax.text(i+0.5, j+0.5, '*',
                       ha='center', va='center',
                       color='black', fontsize=14, fontweight='bold')

    ax.set_title('Matriz de Correlación con Significancia Estadística\n(*) p-value ≤ 0.05',
                fontsize=14, fontweight='bold')

    plt.tight_layout()
    plt.savefig(f'{output_prefix}_significancia.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 5. MAPA DE CORRELACIÓN CIRCULAR (Radial)
    from math import pi

    fig, ax = plt.subplots(figsize=(12, 12), subplot_kw={'projection': 'polar'})

    # Preparar datos para visualización radial
    n_vars = len(corr_with_score)
    angles = [i * 2 * pi / n_vars for i in range(n_vars)]

    # Valores positivos y negativos
    pos_values = corr_with_score.clip(lower=0)
    neg_values = corr_with_score.clip(upper=0).abs()

    # Barras para correlaciones positivas
    bars_pos = ax.bar(angles, pos_values.values, width=0.4,
                      color='#2ecc71', alpha=0.7, label='Correlación Positiva')

    # Barras para correlaciones negativas (hacia adentro)
    bars_neg = ax.bar(angles, -neg_values.values, width=0.4,
                      color='#e74c3c', alpha=0.7, label='Correlación Negativa')

    # Personalización
    ax.set_xticks(angles)
    ax.set_xticklabels(corr_with_score.index, fontsize=10)
    ax.set_ylim(-1, 1)
    ax.set_yticks([-1, -0.5, 0, 0.5, 1])
    ax.set_yticklabels(['-1.0', '-0.5', '0.0', '0.5', '1.0'])
    ax.set_title('Mapa Radial de Correlaciones con Score', fontsize=16, fontweight='bold', pad=20)
    ax.legend(loc='upper right', bbox_to_anchor=(1.1, 1.1))
    ax.grid(True, alpha=0.3)

    # Añadir valores
    for angle, var, val in zip(angles, corr_with_score.index, corr_with_score.values):
        r = val if val > 0 else 0
        ax.text(angle, r + 0.05, f'{val:.2f}',
                ha='center', va='bottom' if val > 0 else 'top',
                fontsize=9, fontweight='bold')

    plt.tight_layout()
    plt.savefig(f'{output_prefix}_radial.png', dpi=300, bbox_inches='tight')
    plt.show()

    # 6. REPORTE DE CORRELACIONES (Texto)
    print("\n" + "="*80)
    print(" REPORTE DE CORRELACIONES CON SCORE")
    print("="*80)

    print("\n📊 TOP 5 CORRELACIONES POSITIVAS MÁS FUERTES:")
    top_pos = corr_with_score.nlargest(5)
    for var, corr_val in top_pos.items():
        if corr_val > 0:
            print(f"   • {var}: {corr_val:.3f}")

    print("\n📉 TOP 5 CORRELACIONES NEGATIVAS MÁS FUERTES:")
    top_neg = corr_with_score.nsmallest(5)
    for var, corr_val in top_neg.items():
        if corr_val < 0:
            print(f"   • {var}: {corr_val:.3f}")

    print("\n📌 INTERPRETACIÓN:")
    for var, corr_val in corr_with_score.abs().nlargest(3).items():
        actual_corr = corr_with_score[var]
        if abs(actual_corr) >= 0.5:
            strength = "MUY FUERTE"
        elif abs(actual_corr) >= 0.3:
            strength = "MODERADA"
        else:
            strength = "DÉBIL"

        direction = "positiva" if actual_corr > 0 else "negativa"

        if var == 'MILLISECONDS':
            print(f"\n   • {var}: Correlación {direction} {strength} ({actual_corr:.3f})")
            print("     → Menos milisegundos (más rápido) → Mayor score")
        elif var == 'POSITION':
            print(f"\n   • {var}: Correlación {direction} {strength} ({actual_corr:.3f})")
            print("     → Mejor posición (número bajo) → Mayor score")
        elif var == 'PACE_DIFF':
            print(f"\n   • {var}: Correlación {direction} {strength} ({actual_corr:.3f})")
            if actual_corr > 0:
                print("     → Mayor diferencia de ritmo (más rápido que promedio) → Mayor score")
            else:
                print("     → Revisar definición de la métrica")

    return {
        'correlation_matrix': corr_matrix,
        'correlation_with_score': corr_with_score,
        'p_values': p_values,
        'df_clean': df_corr
    }

# Función simplificada para un mapa rápido
def mapa_correlacion_rapido(merged_df):
    """Versión rápida para un solo mapa de calor"""

    # Seleccionar variables
    vars_to_plot = ['LAP', 'POSITION', 'MILLISECONDS', 'PIT_BINARY',
                    'MILLISECONDS_CUMULATIVE', 'PACE_DIFF', 'POSITION_CHANGE', 'score']

    available = [v for v in vars_to_plot if v in merged_df.columns]

    # Preparar datos
    df_plot = merged_df[available].dropna()

    # Winsorizar
    for col in df_plot.columns:
        if df_plot[col].dtype in ['float64', 'int64'] and col != 'PIT_BINARY':
            df_plot[col] = stats.mstats.winsorize(df_plot[col], limits=[0.01, 0.01])

    # Calcular correlación
    corr = df_plot.corr()

    # Crear mapa
    plt.figure(figsize=(12, 10))
    mask = np.triu(np.ones_like(corr, dtype=bool))

    sns.heatmap(corr,
                mask=mask,
                annot=True,
                fmt='.2f',
                cmap='RdBu_r',
                center=0,
                square=True,
                linewidths=2,
                cbar_kws={"shrink": 0.8, "label": "Correlación"},
                annot_kws={"size": 10, "weight": "bold"})

    plt.title('Mapa de Correlación - Variables de Rendimiento vs Score',
              fontsize=16, fontweight='bold', pad=20)
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    return corr

# EJECUCIÓN PRINCIPAL
# Asumiendo que ya tienes 'merged_df' de tu código anterior

# Opción 1: Mapa de correlación completo (recomendado)
resultados_corr = crear_mapa_correlacion_completo(merged_df, 'analisis_score')

# Opción 2: Mapa rápido si prefieres solo lo esencial
# matriz_correlacion = mapa_correlacion_rapido(merged_df)

# Acceder a los resultados
print("\n✓ Análisis completado. Puedes acceder a:")
print("  - resultados_corr['correlation_matrix']: Matriz de correlación")
print("  - resultados_corr['correlation_with_score']: Correlaciones con score")
print("  - resultados_corr['p_values']: Significancia estadística")