# -*- coding: utf-8 -*-
"""Estructura_PS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUE7TPqmhNn0jRFARItmb91wrM_BE7vv

# 1. CARGA
"""

!pip install ipywidgets scikit-learn xgboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

from sklearn.preprocessing import StandardScaler, MinMaxScaler


from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.neural_network import MLPRegressor # MLP = multi layer perceptron
from sklearn.svm import SVR

pd.set_option('display.max_columns', None)
pit_stops = pd.read_csv('PIT_STOPS.csv')
pit_stops.head()

"""#2. EXPLORACIÓN"""

print("Info for Pit Stops DataFrame:")
pit_stops.info()
print("\nDescriptive statistics for Pit Stops DataFrame:")
pit_stops.describe()

print("Missing values in Pit Stops DataFrame:")
pit_stops.isnull().sum()

"""#3. LIMPIEZA"""

from datetime import date

today = date.today()
print(today)
# Output example: 2024-03-09

import pandas as pd

# Reload pit_stops to ensure it's defined and clean (if kernel was reset)
pit_stops = pd.read_csv('PIT_STOPS.csv')

# Convert DATETIME_PITSTOP to datetime objects first, if it's not already
pit_stops['DATETIME_PITSTOP'] = pd.to_datetime(pit_stops['DATETIME_PITSTOP'], errors='coerce')

# Now, extract only the date part, leaving only year, month, day
pit_stops['DATETIME_PITSTOP'] = pit_stops['DATETIME_PITSTOP'].dt.date

pit_stops

pit_stops['DRIVERREF'] = pit_stops['DRIVERREF'].apply(lambda x: x.split('_', 1)[-1] if isinstance(x, str) and '_' in x else x)
pit_stops.head()

pit_stops

"""pit_stops['DRIVERREF'].fillna('unknown', inplace=True)
print('Missing values after imputing DRIVERREF:')
print(pit_stops.isnull().sum())
"""

# Create a mapping from DRIVERID to DRIVERREF using non-null entries
# For each DRIVERID, get the first non-null DRIVERREF
driver_id_to_ref_map = pit_stops.dropna(subset=['DRIVERREF']).groupby('DRIVERID')['DRIVERREF'].first()

# Fill null DRIVERREF values using the created mapping
pit_stops['DRIVERREF'] = pit_stops['DRIVERREF'].fillna(pit_stops['DRIVERID'].map(driver_id_to_ref_map))

# Fill any remaining null DRIVERREF values with 'unknown' (addressing FutureWarning)
pit_stops['DRIVERREF'] = pit_stops['DRIVERREF'].fillna('unknown')

print('Missing values after imputing DRIVERREF by DRIVERID and filling remaining with unknown:')
print(pit_stops.isnull().sum())

print('Missing values after handling:')
pit_stops.isnull().sum()

"""#5. CONVERSIÓN DE TIPOS"""

# Conversión de tipos
pit_stops["RACEID"] = pit_stops["RACEID"].astype("int")
pit_stops["DRIVERID"] = pit_stops["DRIVERID"].astype("int")
pit_stops["STOP"] = pit_stops["STOP"].astype("int")
pit_stops["LAP"] = pit_stops["LAP"].astype("int")

pit_stops["MILLISECONDS"] = pit_stops["MILLISECONDS"].astype("float")

# convertir a datetime
#pit_stops["DATETIME_PITSTOP"] = pd.to_datetime(pit_stops["DATETIME_PITSTOP"])

"""#6. FEATURE ENGINEERING"""

pit_stops["PIT_DURATION_SEC"] = pit_stops["MILLISECONDS"] / 1000

avg_pit = pit_stops["MILLISECONDS"].mean()

pit_stops["TOTAL_STOPS_DRIVER"] = pit_stops.groupby(
    ["RACEID", "DRIVERID"]
)["STOP"].transform("max")

"""#10 VALIDACIÓN FINAL"""

pit_stops.shape

pit_stops.head()

ps_mod = pit_stops[['RACEID','TOTAL_STOPS_DRIVER', 'STOP']]
ps_mod.head()

ps_mod

"""TOTAL_STOPS_DRIVER, STOP"""

ps_mod.to_csv('ps_mod.csv', index=False)