# -*- coding: utf-8 -*-
"""dataprep2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrQYli0i28JDY29-HjZnu5ZoNtQ9LwGb

# Lab 1 – Course Tools & ML Basics Setup
"""

import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import pandas as pd

# Load the dataset
df = pd.read_csv('/kaggle/input/datasets/kaushiksuresh147/formula-1-trending-tweets/F1_tweets.csv')

# first 5 rows
df.head()

#Dataset size
df.shape

# column names and data types
df.info()

#  summary statistics
df.describe()

"""# Lab 2 – Exploratory Data Analysis & Data Preprocessing


"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/kaggle/input/datasets/kaushiksuresh147/formula-1-trending-tweets/F1_tweets.csv', low_memory=False)

df.head()

df.shape
df.info()

plt.hist(df['user_followers'], bins=20)

plt.title("Distribution of User Followers")
plt.xlabel("Number of Followers")
plt.ylabel("Frequency")

plt.show()

sns.boxplot(x=df['user_friends'])

plt.title("Boxplot of User Friends")

plt.show()

df['user_verified'].value_counts().plot(kind='bar')

plt.title("Verified vs Non Verified Users")
plt.xlabel("Verification Status")
plt.ylabel("Number of Users")

plt.show()

numeric_df = df.select_dtypes(include=['float64','int64'])

plt.figure(figsize=(8,6))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

df.isnull().sum()

df = df.ffill()

df.duplicated().sum()

df = df.drop_duplicates()

from sklearn.preprocessing import StandardScaler

df['user_followers'] = pd.to_numeric(df['user_followers'], errors='coerce')
df['user_friends'] = pd.to_numeric(df['user_friends'], errors='coerce')

scaler = StandardScaler()

df[['user_followers','user_friends']] = scaler.fit_transform(
    df[['user_followers','user_friends']]
)

df.head()
df.info()

df.head()
df.info()